#!/usr/bin/env python3
"""Audit Raw672 initial geometry without opening labels, metadata, FMT, or IVD.

The audit replays the two geometry predicates that stopped
Verify_DimensionlessDeformationFMT_1.1 job 51088712.  Independently, it asks
whether each observed six-neighbour configuration lies inside a conservative
IEEE-754 float32 rounding envelope generated by one common positive pre-storage
distance.  It never changes the frozen verifier or emits classifier metrics.
"""

from __future__ import annotations

import argparse
from contextlib import contextmanager
import csv
from dataclasses import dataclass
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
from types import MappingProxyType
from typing import Any, BinaryIO, Callable, Iterable, Iterator, Mapping, Sequence

import numpy as np
import yaml


ROOT = Path(__file__).resolve().parents[1]
EXPERIMENT = "Other_DimensionlessInputGeometryAudit_1.1"
CONFIG_PATH = ROOT / "config" / "Other_DimensionlessInputGeometryAudit_1.1.yaml"
EXPECTED_CONFIG_SHA256 = (
    "c874a8d9f6abbab452c6543139073eea2ac88e3db99ea13f78e0c3d43e03f566"
)

MANIFEST_SCHEMA = "pathline_template_matching.long_arc_train_cache_input.v1"
SUMMARY_SCHEMA = "pathline_template_matching.dimensionless_input_geometry_audit.v1"
COMPLETE_SCHEMA = "pathline_template_matching.dimensionless_input_geometry_audit_complete.v1"

ALLOWED_MEMBERS = (
    "raw_features",
    "valid_scale_id",
    "valid_center_seed_index",
    "valid_scale_block_index",
    "valid_assigned_row_index",
    "seeds_xyz",
)
REQUIRED_FORBIDDEN_MEMBERS = (
    "valid_labels",
    "reference_labels_all",
    "metadata_json",
    "fmt_features",
    "ivd_values_all",
    "ivd_volume",
    "valid_mask",
    "center_sample_time",
    "line_steps",
    "line_travel",
    "line_end_time",
    "line_reached_target",
    "scale_assignment",
)
FORBIDDEN_DATASETS = ("tangaroa", "smokeBuoyancy")
FAMILY_ORDER = (
    "half_cylinder",
    "delta_wing",
    "f22_raptor",
    "channel",
    "boeing_747",
)
DIRECTION_AXES = np.asarray((0, 0, 1, 1, 2, 2), dtype=np.int64)
DIRECTION_SIGNS = np.asarray((1.0, -1.0, 1.0, -1.0, 1.0, -1.0), dtype=np.float64)
EXPECTED_AXIS_MASK = np.asarray(
    (
        (True, False, False),
        (True, False, False),
        (False, True, False),
        (False, True, False),
        (False, False, True),
        (False, False, True),
    ),
    dtype=bool,
)

SHARD_FIELDS = (
    "dataset",
    "physical_family",
    "source_ordinal",
    "source_index",
    "cache_size_bytes",
    "cache_sha256",
    "row_count",
    "observed_scale_count",
    "center_origin_fail_count",
    "axis_support_fail_count",
    "zero_dx_count",
    "six_norm_fail_count",
    "opposite_pair_fail_count",
    "either_gate_fail_count",
    "rounding_envelope_feasible_count",
    "rounding_envelope_infeasible_count",
    "gate_fail_explained_by_rounding_count",
    "gate_fail_unexplained_count",
    "common_scale_envelope_feasible_count",
    "common_scale_envelope_infeasible_count",
    "relative_spread_p50",
    "relative_spread_p90",
    "relative_spread_p99",
    "relative_spread_p999",
    "relative_spread_max",
    "max_abs_norm_difference",
    "max_opposite_pair_residual",
    "first_gate_fail_raw_row",
    "first_gate_fail_scale_id",
    "first_gate_fail_center_seed_index",
    "first_gate_fail_assigned_row_index",
)

SCALE_FIELDS = (
    "dataset",
    "physical_family",
    "source_ordinal",
    "source_index",
    "scale_id",
    "block_index",
    "row_count",
    "center_origin_fail_count",
    "axis_support_fail_count",
    "zero_dx_count",
    "six_norm_fail_count",
    "opposite_pair_fail_count",
    "either_gate_fail_count",
    "rounding_envelope_feasible_count",
    "rounding_envelope_infeasible_count",
    "gate_fail_explained_by_rounding_count",
    "gate_fail_unexplained_count",
    "common_h_envelope_feasible",
    "common_h_interval_low",
    "common_h_interval_high",
    "realized_dx_min",
    "realized_dx_mean",
    "realized_dx_max",
    "relative_spread_p99",
    "relative_spread_max",
    "max_abs_norm_difference",
    "max_opposite_pair_residual",
)


def _require(condition: object, message: str) -> None:
    if not condition:
        raise ValueError(message)


def _lower_hex(value: object, length: int = 64) -> bool:
    return (
        isinstance(value, str)
        and len(value) == length
        and all(character in "0123456789abcdef" for character in value)
    )


def sha256_file(path: str | Path, chunk_bytes: int = 8 * 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as source:
        while block := source.read(chunk_bytes):
            digest.update(block)
    return digest.hexdigest()


def _canonical_json_sha256(value: Any) -> str:
    payload = json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def _json_safe(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {str(key): _json_safe(item) for key, item in value.items()}
    if isinstance(value, (tuple, list)):
        return [_json_safe(item) for item in value]
    if isinstance(value, (np.bool_, bool)):
        return bool(value)
    if isinstance(value, (np.integer, int)):
        return int(value)
    if isinstance(value, (np.floating, float)):
        numeric = float(value)
        _require(np.isfinite(numeric), "JSON artifact contains NaN or infinity")
        return numeric
    if isinstance(value, Path):
        return str(value)
    return value


def _manifest_with_self_hash(payload: Mapping[str, Any]) -> dict[str, Any]:
    output = dict(_json_safe(payload))
    _require("content_sha256" not in output, "manifest already contains a self hash")
    output["content_sha256"] = _canonical_json_sha256(output)
    return output


def authenticate_self_hash(payload: Mapping[str, Any]) -> None:
    content = dict(payload)
    observed = content.pop("content_sha256", None)
    _require(_lower_hex(observed), "manifest self hash is missing")
    _require(observed == _canonical_json_sha256(content), "manifest self hash mismatch")


@dataclass(frozen=True)
class AuditPlan:
    path: Path
    sha256: str
    raw: Mapping[str, Any]
    dataset_order: tuple[str, ...]
    family_by_dataset: Mapping[str, str]
    forbidden_datasets: tuple[str, ...]
    allowed_members: tuple[str, ...]
    forbidden_members: tuple[str, ...]
    manifest_path: Path
    manifest_size_bytes: int
    manifest_sha256: str
    manifest_rows_sha256: str
    manifest_row_count: int
    manifest_input_scope: str
    cache_builder_git_commit: str
    parent_main_config_sha256: str
    geometry_rtol: float
    geometry_atol: float
    assigned_seed_count: int
    center_seed_count: int


@dataclass(frozen=True)
class CacheRow:
    dataset: str
    physical_family: str
    source_ordinal: int
    source_index: int
    path: Path
    size_bytes: int
    sha256: str


@dataclass(frozen=True)
class GeometryAudit:
    scale_ids: np.ndarray
    center_indices: np.ndarray
    assigned_indices: np.ndarray
    center_origin_fail: np.ndarray
    axis_support_fail: np.ndarray
    zero_dx: np.ndarray
    six_norm_fail: np.ndarray
    opposite_pair_fail: np.ndarray
    either_gate_fail: np.ndarray
    realized_dx: np.ndarray
    relative_spread: np.ndarray
    abs_norm_difference: np.ndarray
    opposite_pair_residual: np.ndarray
    rounding_low: np.ndarray
    rounding_high: np.ndarray
    rounding_feasible: np.ndarray


def load_plan(config_path: str | Path = CONFIG_PATH) -> AuditPlan:
    """Freeze the complete audit definition before any parent manifest access."""

    path = Path(config_path).resolve()
    content = path.read_bytes()
    digest = hashlib.sha256(content).hexdigest()
    _require(digest == EXPECTED_CONFIG_SHA256, "frozen geometry-audit config SHA-256 drifted")
    raw = yaml.safe_load(content.decode("utf-8"))
    _require(isinstance(raw, Mapping), "geometry-audit config root is invalid")
    _require(raw.get("experiment") == EXPERIMENT, "geometry-audit experiment drifted")
    _require(
        raw.get("status") == "frozen_after_job_51088712_before_full_32_shard_audit",
        "geometry-audit freeze history drifted",
    )

    evidence = raw.get("evidence_scope")
    parent = raw.get("parent_identity")
    access = raw.get("cache_member_access")
    arrays = raw.get("array_contract")
    replay = raw.get("frozen_geometry_gate_replay")
    hypothesis = raw.get("quantization_hypothesis")
    output = raw.get("output_contract")
    execution = raw.get("execution")
    _require(
        all(
            isinstance(value, Mapping)
            for value in (evidence, parent, access, arrays, replay, hypothesis, output, execution)
        ),
        "geometry-audit config sections are incomplete",
    )
    assert isinstance(evidence, Mapping)
    assert isinstance(parent, Mapping)
    assert isinstance(access, Mapping)
    assert isinstance(arrays, Mapping)
    assert isinstance(replay, Mapping)
    assert isinstance(hypothesis, Mapping)
    assert isinstance(output, Mapping)
    assert isinstance(execution, Mapping)

    dataset_order = tuple(str(value) for value in evidence.get("allowed_datasets", ()))
    family_raw = evidence.get("physical_families")
    _require(isinstance(family_raw, Mapping), "physical-family mapping is missing")
    assert isinstance(family_raw, Mapping)
    _require(tuple(family_raw) == FAMILY_ORDER, "physical-family order drifted")
    family_by_dataset: dict[str, str] = {}
    flattened: list[str] = []
    for family in FAMILY_ORDER:
        datasets = tuple(str(value) for value in family_raw.get(family, ()))
        _require(datasets, f"physical family is empty: {family}")
        for dataset in datasets:
            _require(dataset not in family_by_dataset, f"dataset is repeated: {dataset}")
            family_by_dataset[dataset] = family
            flattened.append(dataset)
    _require(tuple(flattened) == dataset_order, "dataset/family order is inconsistent")
    _require(len(dataset_order) == len(set(dataset_order)) == 8, "exactly eight train datasets are required")
    forbidden_datasets = tuple(str(value) for value in evidence.get("forbidden_datasets", ()))
    _require(forbidden_datasets == FORBIDDEN_DATASETS, "forbidden dataset set drifted")
    _require(not set(dataset_order) & set(forbidden_datasets), "allowed/forbidden datasets overlap")

    allowed_members = tuple(str(value) for value in access.get("allowed_members_in_exact_order", ()))
    forbidden_members = tuple(str(value) for value in access.get("forbidden_members", ()))
    _require(allowed_members == ALLOWED_MEMBERS, "allowed cache-member list drifted")
    _require(forbidden_members == REQUIRED_FORBIDDEN_MEMBERS, "forbidden cache-member list drifted")
    _require(not set(allowed_members) & set(forbidden_members), "cache-member allow/deny lists overlap")
    _require(
        access.get("whole_cache_file_authentication_before_member_access") is True,
        "whole-file authentication gate drifted",
    )

    manifest = parent.get("cache_input_manifest")
    _require(isinstance(manifest, Mapping), "cache input manifest identity is missing")
    assert isinstance(manifest, Mapping)
    _require(manifest.get("schema") == MANIFEST_SCHEMA, "cache manifest schema drifted")
    _require(int(manifest.get("row_count", -1)) == 32, "cache manifest row count drifted")
    _require(manifest.get("test_dataset_access") is False, "test dataset access must remain false")
    _require(
        parent.get("experiment") == "mainExp_TemplateMatching_3.1"
        and parent.get("cache_schema") == "pathline_template_matching.phase31_cache.v1",
        "parent cache identity drifted",
    )
    cache_commit = str(parent.get("cache_builder_git_commit", ""))
    main_config_sha = str(parent.get("main_config_sha256", ""))
    manifest_sha = str(manifest.get("sha256", ""))
    rows_sha = str(manifest.get("rows_content_sha256", ""))
    _require(_lower_hex(cache_commit, 40), "cache builder commit is invalid")
    _require(_lower_hex(main_config_sha), "parent main-config SHA-256 is invalid")
    _require(_lower_hex(manifest_sha) and _lower_hex(rows_sha), "manifest hash identity is invalid")

    norm_gate = replay.get("six_norm_equality")
    midpoint_gate = replay.get("opposite_pair_midpoint")
    _require(isinstance(norm_gate, Mapping) and isinstance(midpoint_gate, Mapping), "geometry tolerances are missing")
    assert isinstance(norm_gate, Mapping)
    assert isinstance(midpoint_gate, Mapping)
    rtol = float(norm_gate.get("rtol", float("nan")))
    atol = float(norm_gate.get("atol", float("nan")))
    _require(
        rtol == float(midpoint_gate.get("rtol", float("nan"))) == 5.0e-5
        and atol == float(midpoint_gate.get("atol", float("nan"))) == 1.0e-7,
        "frozen geometry tolerances drifted",
    )
    _require(
        hypothesis.get("scale_table_or_grid_metadata_use") == "forbidden"
        and hypothesis.get("midpoint_tie_policy") == "closed_conservative_envelope",
        "metadata-free rounding-envelope contract drifted",
    )
    _require(output.get("overwrite") == "forbidden", "output overwrite policy drifted")
    _require(
        tuple(output.get("exact_files_before_completion", ()))
        == ("per_shard_geometry.csv", "per_scale_geometry.csv", "summary.json")
        and output.get("completion_file_written_last") == "RUN_COMPLETE.json",
        "output file population drifted",
    )
    _require(
        execution.get("required_cpu_constraint") == "cpu_amd_epyc_7702"
        and int(execution.get("required_threads", -1)) == 32
        and int(execution.get("required_memory_gib", -1)) == 128,
        "Ibex CPU execution contract drifted",
    )
    seeds_contract = arrays.get("seeds_xyz")
    center_contract = arrays.get("valid_center_seed_index")
    _require(isinstance(seeds_contract, Mapping) and isinstance(center_contract, Mapping), "seed contracts are missing")
    assert isinstance(seeds_contract, Mapping)
    assert isinstance(center_contract, Mapping)
    assigned_seed_count = int(seeds_contract.get("shape", (-1, -1))[0])
    center_seed_count = int(center_contract.get("valid_range", (-1, -1))[1]) + 1
    _require(assigned_seed_count == 128000 and center_seed_count == 64000, "seed population contract drifted")

    return AuditPlan(
        path=path,
        sha256=digest,
        raw=MappingProxyType(dict(raw)),
        dataset_order=dataset_order,
        family_by_dataset=MappingProxyType(family_by_dataset),
        forbidden_datasets=forbidden_datasets,
        allowed_members=allowed_members,
        forbidden_members=forbidden_members,
        manifest_path=Path(str(manifest.get("path"))),
        manifest_size_bytes=int(manifest.get("size_bytes", -1)),
        manifest_sha256=manifest_sha,
        manifest_rows_sha256=rows_sha,
        manifest_row_count=int(manifest.get("row_count", -1)),
        manifest_input_scope=str(manifest.get("input_scope", "")),
        cache_builder_git_commit=cache_commit,
        parent_main_config_sha256=main_config_sha,
        geometry_rtol=rtol,
        geometry_atol=atol,
        assigned_seed_count=assigned_seed_count,
        center_seed_count=center_seed_count,
    )


@dataclass(frozen=True)
class _OpenFileIdentity:
    size_bytes: int
    mtime_ns: int
    ctime_ns: int
    device: int
    inode: int
    mode: int

    @classmethod
    def from_stat(cls, value: os.stat_result) -> "_OpenFileIdentity":
        return cls(
            size_bytes=int(value.st_size),
            mtime_ns=int(value.st_mtime_ns),
            ctime_ns=int(value.st_ctime_ns),
            device=int(value.st_dev),
            inode=int(value.st_ino),
            mode=int(value.st_mode),
        )


@dataclass(frozen=True)
class _AuthenticatedOpenFile:
    stream: BinaryIO
    size_bytes: int
    sha256: str


@contextmanager
def _authenticated_open_file(
    path: str | Path,
    *,
    expected_size: int,
    expected_sha256: str,
) -> Iterator[_AuthenticatedOpenFile]:
    """Hash one no-follow descriptor before any content is consumed."""

    source = Path(path)
    flags = os.O_RDONLY | getattr(os, "O_BINARY", 0) | getattr(os, "O_NOFOLLOW", 0)
    path_before = _OpenFileIdentity.from_stat(source.stat(follow_symlinks=False))
    descriptor = os.open(os.fspath(source), flags)
    stream = os.fdopen(descriptor, "rb")
    try:
        descriptor_before = _OpenFileIdentity.from_stat(os.fstat(stream.fileno()))
        _require(descriptor_before == path_before, f"file identity changed before open: {source}")
        digest = hashlib.sha256()
        byte_count = 0
        while True:
            block = stream.read(8 * 1024 * 1024)
            if not block:
                break
            digest.update(block)
            byte_count += len(block)
        descriptor_after_hash = _OpenFileIdentity.from_stat(os.fstat(stream.fileno()))
        path_after_hash = _OpenFileIdentity.from_stat(source.stat(follow_symlinks=False))
        _require(
            descriptor_before == descriptor_after_hash == path_after_hash,
            f"file identity changed while hashing: {source}",
        )
        actual_sha = digest.hexdigest()
        _require(
            byte_count == expected_size == descriptor_before.size_bytes,
            f"file size mismatch: {source}",
        )
        _require(actual_sha == expected_sha256, f"file SHA-256 mismatch: {source}")
        stream.seek(0)
        yield _AuthenticatedOpenFile(stream, byte_count, actual_sha)
        descriptor_final = _OpenFileIdentity.from_stat(os.fstat(stream.fileno()))
        path_final = _OpenFileIdentity.from_stat(source.stat(follow_symlinks=False))
        _require(
            descriptor_final == descriptor_before == path_final,
            f"file identity changed while consuming content: {source}",
        )
    finally:
        stream.close()


def load_cache_rows(plan: AuditPlan) -> tuple[tuple[CacheRow, ...], Mapping[str, Any]]:
    """Authenticate the frozen train manifest and resolve exactly 32 cache files."""

    with _authenticated_open_file(
        plan.manifest_path,
        expected_size=plan.manifest_size_bytes,
        expected_sha256=plan.manifest_sha256,
    ) as opened:
        manifest = json.loads(opened.stream.read().decode("utf-8"))
    _require(isinstance(manifest, Mapping), "cache input manifest root is invalid")
    rows_value = manifest.get("rows")
    _require(isinstance(rows_value, list), "cache input manifest rows are missing")
    _require(manifest.get("schema") == MANIFEST_SCHEMA, "cache input manifest schema drifted")
    _require(manifest.get("experiment") == "Verify_LongArcHorizon_1.1", "cache manifest producer drifted")
    _require(manifest.get("parent_experiment") == "mainExp_TemplateMatching_3.1", "cache manifest parent drifted")
    _require(manifest.get("input_scope") == plan.manifest_input_scope, "cache manifest scope drifted")
    _require(manifest.get("git_commit") == plan.cache_builder_git_commit, "cache builder commit drifted")
    _require(manifest.get("main_config_sha256") == plan.parent_main_config_sha256, "parent config identity drifted")
    _require(manifest.get("test_dataset_access") is False, "cache manifest accessed test data")
    _require(int(manifest.get("row_count", -1)) == plan.manifest_row_count == len(rows_value), "cache manifest row count drifted")
    observed_rows_sha = _canonical_json_sha256(rows_value)
    _require(
        manifest.get("rows_content_sha256") == plan.manifest_rows_sha256 == observed_rows_sha,
        "cache manifest row-content SHA-256 drifted",
    )

    rows: list[CacheRow] = []
    for raw_row in rows_value:
        _require(isinstance(raw_row, Mapping), "cache manifest row is invalid")
        assert isinstance(raw_row, Mapping)
        dataset = str(raw_row.get("dataset", ""))
        _require(dataset in plan.family_by_dataset, f"unauthorized dataset: {dataset}")
        source_ordinal = int(raw_row.get("source_ordinal", -1))
        source_index = int(raw_row.get("source_index", -1))
        path = Path(str(raw_row.get("cache_path", "")))
        normalized = path.as_posix()
        _require("/primitive_cache/train/" in normalized, f"non-train cache path: {path}")
        _require(not any(name in normalized for name in plan.forbidden_datasets), f"forbidden dataset path: {path}")
        sha = str(raw_row.get("cache_file_sha256", ""))
        size = int(raw_row.get("cache_size_bytes", -1))
        _require(_lower_hex(sha) and size > 0, f"invalid cache identity: {path}")
        rows.append(
            CacheRow(
                dataset=dataset,
                physical_family=plan.family_by_dataset[dataset],
                source_ordinal=source_ordinal,
                source_index=source_index,
                path=path,
                size_bytes=size,
                sha256=sha,
            )
        )
    _require(len(rows) == 32, "audit requires exactly 32 cache shards")
    _require(len({(row.dataset, row.source_ordinal) for row in rows}) == 32, "duplicate cache shard identity")
    _require(len({row.path for row in rows}) == 32, "duplicate cache path")
    for dataset in plan.dataset_order:
        ordinals = sorted(row.source_ordinal for row in rows if row.dataset == dataset)
        _require(ordinals == [0, 1, 2, 3], f"source ordinals drifted: {dataset}")
    rows.sort(key=lambda row: (plan.dataset_order.index(row.dataset), row.source_ordinal))
    identity = {
        "path": str(plan.manifest_path),
        "size_bytes": plan.manifest_size_bytes,
        "sha256": plan.manifest_sha256,
        "schema": MANIFEST_SCHEMA,
        "row_count": 32,
        "rows_content_sha256": observed_rows_sha,
        "test_dataset_access": False,
    }
    return tuple(rows), MappingProxyType(identity)


def _load_cache_members(plan: AuditPlan, row: CacheRow) -> dict[str, np.ndarray]:
    """Open exactly the allowlisted six members after whole-NPZ authentication."""

    _require(plan.allowed_members == ALLOWED_MEMBERS, "runtime member allowlist drifted")
    _require(not set(plan.allowed_members) & set(plan.forbidden_members), "runtime member lists overlap")
    with _authenticated_open_file(
        row.path,
        expected_size=row.size_bytes,
        expected_sha256=row.sha256,
    ) as opened:
        with np.load(opened.stream, allow_pickle=False) as archive:
            arrays = {
                name: np.array(archive[name], copy=True, order="C")
                for name in plan.allowed_members
            }
    _require(tuple(arrays) == ALLOWED_MEMBERS, "opened cache-member order drifted")
    return arrays


def _validate_arrays(plan: AuditPlan, row: CacheRow, arrays: Mapping[str, np.ndarray]) -> None:
    _require(tuple(arrays) == ALLOWED_MEMBERS, f"{row.path}: cache-member population drifted")
    raw = np.asarray(arrays["raw_features"])
    count = len(raw)
    _require(
        count > 0
        and raw.dtype == np.dtype(np.float32)
        and raw.shape == (count, 672)
        and np.isfinite(raw).all(),
        f"{row.path}: Raw672 dtype/shape/finite contract drifted",
    )
    expected = (
        (np.asarray(arrays["valid_scale_id"]), np.dtype(np.int32)),
        (np.asarray(arrays["valid_center_seed_index"]), np.dtype(np.int64)),
        (np.asarray(arrays["valid_scale_block_index"]), np.dtype(np.int8)),
        (np.asarray(arrays["valid_assigned_row_index"]), np.dtype(np.int64)),
    )
    _require(
        all(values.dtype == dtype and values.shape == (count,) for values, dtype in expected),
        f"{row.path}: identity-array contract drifted",
    )
    scale_ids, center_indices, block_indices, assigned_indices = (item[0] for item in expected)
    _require(np.all((scale_ids >= 0) & (scale_ids < 2000)), f"{row.path}: scale ID drifted")
    _require(
        np.all((center_indices >= 0) & (center_indices < plan.center_seed_count)),
        f"{row.path}: center seed index drifted",
    )
    _require(np.all((block_indices >= 0) & (block_indices < 2)), f"{row.path}: block index drifted")
    _require(
        np.array_equal(block_indices, (scale_ids >= 1000).astype(np.int8)),
        f"{row.path}: scale/block identity drifted",
    )
    _require(
        np.array_equal(
            assigned_indices,
            block_indices.astype(np.int64) * plan.center_seed_count + center_indices,
        ),
        f"{row.path}: assigned-row identity drifted",
    )
    for block in (0, 1):
        selected = center_indices[block_indices == block]
        _require(len(selected) == len(np.unique(selected)), f"{row.path}: duplicate center within block")
    seeds = np.asarray(arrays["seeds_xyz"])
    _require(
        seeds.dtype == np.dtype(np.float64)
        and seeds.shape == (plan.assigned_seed_count, 3)
        and np.isfinite(seeds).all(),
        f"{row.path}: seeds_xyz dtype/shape/finite contract drifted",
    )
    _require(np.all((assigned_indices >= 0) & (assigned_indices < len(seeds))), f"{row.path}: assigned-row index out of range")


def _rounding_cell(values: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    values32 = np.asarray(values, dtype=np.float32)
    previous = np.nextafter(values32, -np.inf, dtype=np.float32).astype(np.float64)
    following = np.nextafter(values32, np.inf, dtype=np.float32).astype(np.float64)
    middle = values32.astype(np.float64)
    return (previous + middle) * 0.5, (middle + following) * 0.5


def _candidate_float32_bounds(
    center32: np.ndarray,
    observed_delta32: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Invert float32(neighbor-center) into a conservative neighbor hull."""

    delta_low, delta_high = _rounding_cell(observed_delta32)
    center64 = center32.astype(np.float64)
    target_low = center64 + delta_low
    target_high = center64 + delta_high
    lower = target_low.astype(np.float32)
    upper = target_high.astype(np.float32)
    lower = np.where(
        lower.astype(np.float64) < target_low,
        np.nextafter(lower, np.inf, dtype=np.float32),
        lower,
    )
    upper = np.where(
        upper.astype(np.float64) > target_high,
        np.nextafter(upper, -np.inf, dtype=np.float32),
        upper,
    )
    for _ in range(4):
        lower_bad = (lower - center32).astype(np.float32) != observed_delta32
        upper_bad = (upper - center32).astype(np.float32) != observed_delta32
        lower = np.where(
            lower_bad,
            np.nextafter(lower, np.inf, dtype=np.float32),
            lower,
        )
        upper = np.where(
            upper_bad,
            np.nextafter(upper, -np.inf, dtype=np.float32),
            upper,
        )
    valid = (
        np.isfinite(lower)
        & np.isfinite(upper)
        & (lower <= upper)
        & ((lower - center32).astype(np.float32) == observed_delta32)
        & ((upper - center32).astype(np.float32) == observed_delta32)
    )
    return lower, upper, valid


def _common_h_rounding_envelope(
    seeds: np.ndarray,
    observed_initial: np.ndarray,
    *,
    eligible: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return each row's conservative common-positive-h interval."""

    count = len(seeds)
    row_index = np.arange(count, dtype=np.int64)[:, None]
    direction_index = np.arange(6, dtype=np.int64)[None, :]
    observed_axis = observed_initial[
        row_index,
        direction_index,
        DIRECTION_AXES[None, :],
    ].astype(np.float32, copy=False)
    seed_axis = np.asarray(seeds, dtype=np.float64)[:, DIRECTION_AXES]
    center32 = seed_axis.astype(np.float32)
    neighbor_low, neighbor_high, candidate_valid = _candidate_float32_bounds(
        center32, observed_axis
    )
    source_low, _ = _rounding_cell(neighbor_low)
    _, source_high = _rounding_cell(neighbor_high)
    direction_low = np.where(
        DIRECTION_SIGNS[None, :] > 0.0,
        source_low - seed_axis,
        seed_axis - source_high,
    )
    direction_high = np.where(
        DIRECTION_SIGNS[None, :] > 0.0,
        source_high - seed_axis,
        seed_axis - source_low,
    )
    row_low = np.max(direction_low, axis=1)
    row_high = np.min(direction_high, axis=1)
    feasible = (
        np.asarray(eligible, dtype=bool)
        & np.all(candidate_valid, axis=1)
        & np.isfinite(row_low)
        & np.isfinite(row_high)
        & (row_high > 0.0)
        & (row_low <= row_high)
    )
    row_low = np.where(feasible, np.maximum(row_low, 0.0), np.inf)
    row_high = np.where(feasible, row_high, -np.inf)
    return row_low, row_high, feasible


def audit_geometry_arrays(plan: AuditPlan, row: CacheRow, arrays: Mapping[str, np.ndarray]) -> GeometryAudit:
    """Compute label-free row diagnostics after strict identity validation."""

    _validate_arrays(plan, row, arrays)
    raw = np.asarray(arrays["raw_features"])
    primitive = raw.reshape((-1, 7, 32, 3), order="C")
    center_initial = primitive[:, 0, 0, :]
    initial = primitive[:, 1:, 0, :].astype(np.float64) - center_initial[:, None, :].astype(np.float64)
    center_origin_fail = np.any(center_initial != np.float32(0.0), axis=1)
    off_axis = np.where(EXPECTED_AXIS_MASK[None, :, :], 0.0, initial)
    axis_support_fail = np.any(off_axis != 0.0, axis=(1, 2))
    with np.errstate(invalid="ignore", over="ignore", divide="ignore"):
        norms = np.linalg.norm(initial, axis=2)
        realized_dx = np.mean(norms, axis=1, dtype=np.float64)
        norm_min = np.min(norms, axis=1)
        norm_max = np.max(norms, axis=1)
        abs_norm_difference = norm_max - norm_min
        relative_spread = abs_norm_difference / realized_dx
    zero_dx = (~np.isfinite(realized_dx)) | (realized_dx <= 0.0)
    norm_close = np.isclose(
        norms,
        norms[:, :1],
        rtol=plan.geometry_rtol,
        atol=plan.geometry_atol,
    )
    six_norm_fail = ~np.all(norm_close, axis=1)
    opposite_close = np.ones(len(raw), dtype=bool)
    pair_residuals: list[np.ndarray] = []
    for plus, minus in ((0, 1), (2, 3), (4, 5)):
        opposite_close &= np.all(
            np.isclose(
                initial[:, plus],
                -initial[:, minus],
                rtol=plan.geometry_rtol,
                atol=plan.geometry_atol,
            ),
            axis=1,
        )
        pair_residuals.append(np.linalg.norm(initial[:, plus] + initial[:, minus], axis=1))
    opposite_pair_fail = ~opposite_close
    opposite_pair_residual = np.max(np.stack(pair_residuals, axis=1), axis=1)
    either_gate_fail = (
        center_origin_fail
        | axis_support_fail
        | zero_dx
        | six_norm_fail
        | opposite_pair_fail
    )
    # A strictly positive physical h can collapse to an observed zero delta
    # when both absolute coordinates round to the same float32 value.  Keep
    # zero-dx rows eligible for inversion; center-origin and off-axis failures
    # cannot arise from the frozen producer expression and remain ineligible.
    eligible = ~(center_origin_fail | axis_support_fail)
    assigned = np.asarray(arrays["valid_assigned_row_index"])
    seeds = np.asarray(arrays["seeds_xyz"])[assigned]
    rounding_low, rounding_high, rounding_feasible = _common_h_rounding_envelope(
        seeds,
        primitive[:, 1:, 0, :],
        eligible=eligible,
    )
    return GeometryAudit(
        scale_ids=np.asarray(arrays["valid_scale_id"]),
        center_indices=np.asarray(arrays["valid_center_seed_index"]),
        assigned_indices=assigned,
        center_origin_fail=center_origin_fail,
        axis_support_fail=axis_support_fail,
        zero_dx=zero_dx,
        six_norm_fail=six_norm_fail,
        opposite_pair_fail=opposite_pair_fail,
        either_gate_fail=either_gate_fail,
        realized_dx=realized_dx,
        relative_spread=relative_spread,
        abs_norm_difference=abs_norm_difference,
        opposite_pair_residual=opposite_pair_residual,
        rounding_low=rounding_low,
        rounding_high=rounding_high,
        rounding_feasible=rounding_feasible,
    )


def _quantile(values: np.ndarray, probability: float) -> float | None:
    finite = np.asarray(values, dtype=np.float64)
    finite = finite[np.isfinite(finite)]
    if len(finite) == 0:
        return None
    return float(np.quantile(finite, probability, method="linear"))


def _maximum(values: np.ndarray) -> float | None:
    finite = np.asarray(values, dtype=np.float64)
    finite = finite[np.isfinite(finite)]
    if len(finite) == 0:
        return None
    return float(np.max(finite))


def summarize_cache_row(
    row: CacheRow,
    audit: GeometryAudit,
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    """Produce one per-shard row and deterministic observed-scale rows."""

    scale_rows: list[dict[str, Any]] = []
    common_scale_feasible = 0
    for scale_id_value in np.unique(audit.scale_ids):
        scale_id = int(scale_id_value)
        selected = audit.scale_ids == scale_id
        row_feasible = audit.rounding_feasible[selected]
        low = audit.rounding_low[selected]
        high = audit.rounding_high[selected]
        common_low = float(np.max(low)) if np.all(row_feasible) else float("inf")
        common_high = float(np.min(high)) if np.all(row_feasible) else float("-inf")
        common_feasible = bool(
            np.all(row_feasible)
            and np.isfinite(common_low)
            and np.isfinite(common_high)
            and common_high > 0.0
            and common_low <= common_high
        )
        common_scale_feasible += int(common_feasible)
        gate = audit.either_gate_fail[selected]
        # The producer assigns one physical dx to every row sharing this exact
        # scale.  Row-wise feasibility is necessary but not sufficient: if the
        # scale-wide intersection is empty, no single producer h explains even
        # the individually feasible failing rows in this group.
        explained = gate & row_feasible & common_feasible
        scale_rows.append(
            {
                "dataset": row.dataset,
                "physical_family": row.physical_family,
                "source_ordinal": row.source_ordinal,
                "source_index": row.source_index,
                "scale_id": scale_id,
                "block_index": int(scale_id >= 1000),
                "row_count": int(np.sum(selected)),
                "center_origin_fail_count": int(np.sum(audit.center_origin_fail[selected])),
                "axis_support_fail_count": int(np.sum(audit.axis_support_fail[selected])),
                "zero_dx_count": int(np.sum(audit.zero_dx[selected])),
                "six_norm_fail_count": int(np.sum(audit.six_norm_fail[selected])),
                "opposite_pair_fail_count": int(np.sum(audit.opposite_pair_fail[selected])),
                "either_gate_fail_count": int(np.sum(gate)),
                "rounding_envelope_feasible_count": int(np.sum(row_feasible)),
                "rounding_envelope_infeasible_count": int(np.sum(~row_feasible)),
                "gate_fail_explained_by_rounding_count": int(np.sum(explained)),
                "gate_fail_unexplained_count": int(np.sum(gate & ~explained)),
                "common_h_envelope_feasible": common_feasible,
                "common_h_interval_low": common_low if common_feasible else None,
                "common_h_interval_high": common_high if common_feasible else None,
                "realized_dx_min": float(np.min(audit.realized_dx[selected])),
                "realized_dx_mean": float(np.mean(audit.realized_dx[selected], dtype=np.float64)),
                "realized_dx_max": float(np.max(audit.realized_dx[selected])),
                "relative_spread_p99": _quantile(audit.relative_spread[selected], 0.99),
                "relative_spread_max": _maximum(audit.relative_spread[selected]),
                "max_abs_norm_difference": _maximum(audit.abs_norm_difference[selected]),
                "max_opposite_pair_residual": _maximum(audit.opposite_pair_residual[selected]),
            }
        )
    gate_indices = np.flatnonzero(audit.either_gate_fail)
    first = int(gate_indices[0]) if len(gate_indices) else -1
    explained_count = int(
        sum(int(scale_row["gate_fail_explained_by_rounding_count"]) for scale_row in scale_rows)
    )
    unexplained_count = int(
        sum(int(scale_row["gate_fail_unexplained_count"]) for scale_row in scale_rows)
    )
    shard_row = {
        "dataset": row.dataset,
        "physical_family": row.physical_family,
        "source_ordinal": row.source_ordinal,
        "source_index": row.source_index,
        "cache_size_bytes": row.size_bytes,
        "cache_sha256": row.sha256,
        "row_count": len(audit.scale_ids),
        "observed_scale_count": len(scale_rows),
        "center_origin_fail_count": int(np.sum(audit.center_origin_fail)),
        "axis_support_fail_count": int(np.sum(audit.axis_support_fail)),
        "zero_dx_count": int(np.sum(audit.zero_dx)),
        "six_norm_fail_count": int(np.sum(audit.six_norm_fail)),
        "opposite_pair_fail_count": int(np.sum(audit.opposite_pair_fail)),
        "either_gate_fail_count": int(np.sum(audit.either_gate_fail)),
        "rounding_envelope_feasible_count": int(np.sum(audit.rounding_feasible)),
        "rounding_envelope_infeasible_count": int(np.sum(~audit.rounding_feasible)),
        "gate_fail_explained_by_rounding_count": explained_count,
        "gate_fail_unexplained_count": unexplained_count,
        "common_scale_envelope_feasible_count": common_scale_feasible,
        "common_scale_envelope_infeasible_count": len(scale_rows) - common_scale_feasible,
        "relative_spread_p50": _quantile(audit.relative_spread, 0.50),
        "relative_spread_p90": _quantile(audit.relative_spread, 0.90),
        "relative_spread_p99": _quantile(audit.relative_spread, 0.99),
        "relative_spread_p999": _quantile(audit.relative_spread, 0.999),
        "relative_spread_max": _maximum(audit.relative_spread),
        "max_abs_norm_difference": _maximum(audit.abs_norm_difference),
        "max_opposite_pair_residual": _maximum(audit.opposite_pair_residual),
        "first_gate_fail_raw_row": first,
        "first_gate_fail_scale_id": int(audit.scale_ids[first]) if first >= 0 else -1,
        "first_gate_fail_center_seed_index": int(audit.center_indices[first]) if first >= 0 else -1,
        "first_gate_fail_assigned_row_index": int(audit.assigned_indices[first]) if first >= 0 else -1,
    }
    return shard_row, scale_rows


def _fsync_parent_directory(parent: Path) -> None:
    if os.name == "nt":
        return
    descriptor = os.open(os.fspath(parent), os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _publish_no_replace(path: Path, writer: Any, *, text_mode: bool) -> str:
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".partial", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        mode = "w" if text_mode else "wb"
        options = {"encoding": "utf-8", "newline": ""} if text_mode else {}
        with os.fdopen(descriptor, mode, **options) as destination:
            descriptor = -1
            writer(destination)
            destination.flush()
            os.fsync(destination.fileno())
        os.link(temporary, path, follow_symlinks=False)
        _fsync_parent_directory(path.parent)
        temporary.unlink()
        _fsync_parent_directory(path.parent)
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        if temporary.exists():
            temporary.unlink()
            _fsync_parent_directory(path.parent)
    return sha256_file(path)


def _csv_value(value: Any) -> Any:
    if value is None:
        return ""
    if isinstance(value, (np.bool_, bool)):
        return int(bool(value))
    if isinstance(value, (np.integer, int)):
        return int(value)
    if isinstance(value, (np.floating, float)):
        numeric = float(value)
        _require(np.isfinite(numeric), "CSV artifact contains NaN or infinity")
        return format(numeric, ".17g")
    return value


def _atomic_csv(
    path: Path,
    fields: Sequence[str],
    rows: Iterable[Mapping[str, Any]],
) -> str:
    rows_tuple = tuple(rows)
    for row in rows_tuple:
        _require(set(row) == set(fields), f"CSV row fields drifted: {path.name}")

    def write(destination: Any) -> None:
        writer = csv.DictWriter(
            destination,
            fieldnames=list(fields),
            extrasaction="raise",
            lineterminator="\n",
        )
        writer.writeheader()
        for row in rows_tuple:
            writer.writerow({name: _csv_value(row[name]) for name in fields})

    return _publish_no_replace(path, write, text_mode=True)


def _atomic_json(path: Path, payload: Mapping[str, Any]) -> str:
    serialized = json.dumps(
        _json_safe(payload),
        ensure_ascii=False,
        sort_keys=True,
        indent=2,
        allow_nan=False,
    ) + "\n"
    return _publish_no_replace(path, lambda stream: stream.write(serialized), text_mode=True)


def _artifact(path: Path, sha256: str, *, row_count: int | None = None) -> dict[str, Any]:
    value: dict[str, Any] = {
        "path": path.name,
        "size_bytes": path.stat().st_size,
        "sha256": sha256,
    }
    if row_count is not None:
        value["row_count"] = int(row_count)
    return value


def _git_identity() -> tuple[str, bool]:
    commit = subprocess.check_output(
        ("git", "rev-parse", "--verify", "HEAD^{commit}"),
        cwd=ROOT,
        text=True,
    ).strip()
    status = subprocess.check_output(
        ("git", "status", "--porcelain=v1", "--untracked-files=all"),
        cwd=ROOT,
        text=True,
    )
    _require(_lower_hex(commit, 40), "Git commit identity is invalid")
    return commit, bool(status.strip())


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _sum_field(rows: Sequence[Mapping[str, Any]], field: str) -> int:
    return int(sum(int(row[field]) for row in rows))


def run_audit(
    plan: AuditPlan,
    output_directory: str | Path,
    *,
    git_commit: str,
    completion_guard: Callable[[], None] | None = None,
) -> Mapping[str, Any]:
    """Authenticate and scan all 32 shards, then publish four immutable files."""

    _require(_lower_hex(git_commit, 40), "audit Git commit must be a full lowercase SHA-1")
    cache_rows, input_identity = load_cache_rows(plan)
    destination = Path(output_directory).resolve()
    if destination.exists():
        raise FileExistsError(f"immutable geometry-audit output exists: {destination}")
    destination.mkdir(parents=True, exist_ok=False)

    shard_rows: list[dict[str, Any]] = []
    scale_rows: list[dict[str, Any]] = []
    authenticated_cache_identities: list[dict[str, Any]] = []
    for cache_row in cache_rows:
        arrays = _load_cache_members(plan, cache_row)
        audit = audit_geometry_arrays(plan, cache_row, arrays)
        shard_summary, observed_scales = summarize_cache_row(cache_row, audit)
        shard_rows.append(shard_summary)
        scale_rows.extend(observed_scales)
        authenticated_cache_identities.append(
            {
                "dataset": cache_row.dataset,
                "source_ordinal": cache_row.source_ordinal,
                "source_index": cache_row.source_index,
                "size_bytes": cache_row.size_bytes,
                "sha256": cache_row.sha256,
            }
        )
        del audit, arrays

    _require(len(shard_rows) == 32, "completed audit did not contain 32 shard rows")
    scale_rows.sort(
        key=lambda value: (
            plan.dataset_order.index(str(value["dataset"])),
            int(value["source_ordinal"]),
            int(value["scale_id"]),
        )
    )
    per_shard_path = destination / "per_shard_geometry.csv"
    per_scale_path = destination / "per_scale_geometry.csv"
    per_shard_sha = _atomic_csv(per_shard_path, SHARD_FIELDS, shard_rows)
    per_scale_sha = _atomic_csv(per_scale_path, SCALE_FIELDS, scale_rows)

    total_gate_fail = _sum_field(shard_rows, "either_gate_fail_count")
    total_explained = _sum_field(shard_rows, "gate_fail_explained_by_rounding_count")
    total_unexplained = _sum_field(shard_rows, "gate_fail_unexplained_count")
    _require(total_gate_fail == total_explained + total_unexplained, "gate-failure accounting drifted")
    if total_unexplained > 0:
        hypothesis_status = "quantization_only_hypothesis_falsified_by_unexplained_gate_failures"
    elif total_gate_fail > 0:
        hypothesis_status = "quantization_explanation_supported_for_all_observed_gate_failures"
    else:
        hypothesis_status = "no_frozen_gate_failure_observed"

    dataset_summary: dict[str, Any] = {}
    for dataset in plan.dataset_order:
        selected = [row for row in shard_rows if row["dataset"] == dataset]
        _require(len(selected) == 4, f"dataset shard population drifted: {dataset}")
        dataset_summary[dataset] = {
            "shard_count": 4,
            "row_count": _sum_field(selected, "row_count"),
            "either_gate_fail_count": _sum_field(selected, "either_gate_fail_count"),
            "gate_fail_explained_by_rounding_count": _sum_field(
                selected, "gate_fail_explained_by_rounding_count"
            ),
            "gate_fail_unexplained_count": _sum_field(selected, "gate_fail_unexplained_count"),
        }

    artifacts = {
        per_shard_path.name: _artifact(per_shard_path, per_shard_sha, row_count=len(shard_rows)),
        per_scale_path.name: _artifact(per_scale_path, per_scale_sha, row_count=len(scale_rows)),
    }
    summary = _manifest_with_self_hash(
        {
            "schema": SUMMARY_SCHEMA,
            "experiment": EXPERIMENT,
            "status": "completed_label_free_geometry_audit",
            "completed_utc": _utc_now(),
            "git_commit": git_commit,
            "config": {
                "path": str(plan.path),
                "sha256": plan.sha256,
            },
            "input_manifest": dict(input_identity),
            "authenticated_cache_file_count": len(authenticated_cache_identities),
            "authenticated_cache_identities_sha256": _canonical_json_sha256(
                authenticated_cache_identities
            ),
            "opened_cache_members_in_exact_order": list(plan.allowed_members),
            "forbidden_cache_members": list(plan.forbidden_members),
            "forbidden_cache_member_open_count": 0,
            "test_dataset_access": False,
            "raw_flow_access": False,
            "cache_sidecar_access": False,
            "label_access": False,
            "metric_access": False,
            "formal_confirmation": False,
            "geometry_gate": {
                "rtol": plan.geometry_rtol,
                "atol": plan.geometry_atol,
                "changed_by_audit": False,
            },
            "rounding_envelope": {
                "source": "Raw672_identity_arrays_and_seeds_xyz_only",
                "scale_table_or_grid_metadata_used": False,
                "midpoint_tie_policy": "closed_conservative_envelope",
                "hypothesis_status": hypothesis_status,
            },
            "counts": {
                "shard_count": len(shard_rows),
                "observed_shard_scale_count": len(scale_rows),
                "row_count": _sum_field(shard_rows, "row_count"),
                "center_origin_fail_count": _sum_field(shard_rows, "center_origin_fail_count"),
                "axis_support_fail_count": _sum_field(shard_rows, "axis_support_fail_count"),
                "zero_dx_count": _sum_field(shard_rows, "zero_dx_count"),
                "six_norm_fail_count": _sum_field(shard_rows, "six_norm_fail_count"),
                "opposite_pair_fail_count": _sum_field(shard_rows, "opposite_pair_fail_count"),
                "either_gate_fail_count": total_gate_fail,
                "gate_fail_explained_by_rounding_count": total_explained,
                "gate_fail_unexplained_count": total_unexplained,
                "rounding_envelope_feasible_count": _sum_field(
                    shard_rows, "rounding_envelope_feasible_count"
                ),
                "rounding_envelope_infeasible_count": _sum_field(
                    shard_rows, "rounding_envelope_infeasible_count"
                ),
            },
            "per_dataset": dataset_summary,
            "artifacts": artifacts,
            "allowed_claim": (
                "label-free frozen-input geometry distribution and whether observed frozen-gate "
                "failures are consistent with the parent float32 cache-production envelope"
            ),
            "forbidden_claims": [
                "classifier_performance",
                "descriptor_improvement",
                "tolerance_change_authorization",
                "Verify_DimensionlessDeformationFMT_1.1_passed",
                "formal_confirmation",
            ],
        }
    )
    summary_path = destination / "summary.json"
    summary_sha = _atomic_json(summary_path, summary)
    _require(
        {path.name for path in destination.iterdir()}
        == {"per_shard_geometry.csv", "per_scale_geometry.csv", "summary.json"},
        "pre-completion output population drifted",
    )
    if completion_guard is not None:
        completion_guard()
    completion = _manifest_with_self_hash(
        {
            "schema": COMPLETE_SCHEMA,
            "experiment": EXPERIMENT,
            "status": "completed",
            "completed_utc": _utc_now(),
            "git_commit": git_commit,
            "config_sha256": plan.sha256,
            "summary_file": summary_path.name,
            "summary_file_sha256": summary_sha,
            "summary_content_sha256": summary["content_sha256"],
            "exact_file_count": 4,
        }
    )
    completion_path = destination / "RUN_COMPLETE.json"
    completion_sha = _atomic_json(completion_path, completion)
    _require(
        {path.name for path in destination.iterdir()}
        == {
            "per_shard_geometry.csv",
            "per_scale_geometry.csv",
            "summary.json",
            "RUN_COMPLETE.json",
        },
        "completed output population drifted",
    )
    return {
        "summary": summary,
        "summary_file_sha256": summary_sha,
        "completion_file_sha256": completion_sha,
        "output_directory": str(destination),
    }


def run(
    config_path: str | Path,
    output_directory: str | Path,
    *,
    expected_git_commit: str,
) -> Mapping[str, Any]:
    plan = load_plan(config_path)
    observed_commit, dirty = _git_identity()
    _require(not dirty, "geometry audit requires a clean committed worktree")
    _require(observed_commit == expected_git_commit, "checkout commit differs from expected commit")
    def require_final_clean_identity() -> None:
        final_commit, final_dirty = _git_identity()
        _require(
            not final_dirty and final_commit == observed_commit,
            "commit or clean worktree changed before completion publication",
        )

    result = run_audit(
        plan,
        output_directory,
        git_commit=observed_commit,
        completion_guard=require_final_clean_identity,
    )
    return result


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default=str(CONFIG_PATH))
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--expected-git-commit", required=True)
    return parser


def main(argv: Sequence[str] | None = None) -> None:
    arguments = _parser().parse_args(argv)
    result = run(
        arguments.config,
        arguments.output_dir,
        expected_git_commit=arguments.expected_git_commit,
    )
    print(
        json.dumps(
            {
                "status": result["summary"]["status"],
                "hypothesis_status": result["summary"]["rounding_envelope"][
                    "hypothesis_status"
                ],
                "counts": result["summary"]["counts"],
                "summary_file_sha256": result["summary_file_sha256"],
                "completion_file_sha256": result["completion_file_sha256"],
                "output_directory": result["output_directory"],
            },
            sort_keys=True,
            allow_nan=False,
        )
    )


if __name__ == "__main__":
    main()
